services:
  geoserver:
    container_name: geonum_geoserver # lui définir un nom
    image: docker.osgeo.org/geoserver:2.26.0 # lui indiquer une image > c'est une trame en gros
    environment:
      - RUN_UNPRIVILEGED=true
      - CHANGE_OWNERSHIP_ON_FOLDERS="/opt /opt/geoserver_data/ /mnt/geoserver_geodata"
      - CORS_ENABLED=true
      - SKIP_DEMO_DATA=true
    ports:
      - "8080:8080" # premier port = port de la machine/port externe, deuxième port = port du contenaire/port interne
    volumes:
      - ./geoserver/opt:/opt/geoserver_data

  web:
    container_name: geonum_web
    image: caddy:latest
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./app/dist/:/srv
